services:
  asgard-pavlov-web:
    image: ${DOCKERHUB_USERNAME}/asgard-pavlov-web:${GITHUB_SHA}
    volumes:
      - ./certbot/www:/app/public/.well-known/acme-challenge
    expose:
      - "3000"
    networks:
      - internal
    restart: unless-stopped

  nginx:
    image: ${DOCKERHUB_USERNAME}/asgard-pavlov-nginx:${GITHUB_SHA}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    depends_on:
      - asgard-pavlov-web
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
      -
networks:
  internal: